[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tofo = "64aTv11S84mx9Nq3Wxih6kGLrqmXM1eFHBMsnSotuKSp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/inaam/.config/solana/id.json"
faucet = "http://localhost:9901" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
